# Generated by Django 5.2.11 on 2026-02-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "request_hash",
                    models.CharField(
                        help_text="Hash of request body for replay detection", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_record",
                        to="payouts.payoutrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Idempotency record",
                "verbose_name_plural": "Idempotency records",
                "ordering": ["-created_at"],
            },
        ),
    ]
