# Generated by Django 5.2.11 on 2026-02-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payouts", "0002_idempotency_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payout_id", models.UUIDField(db_index=True)),
                ("action", models.CharField(max_length=32)),
                ("old_value", models.CharField(blank=True, max_length=100)),
                ("new_value", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payout audit log",
                "verbose_name_plural": "Payout audit logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
