# Generated by Django 5.2.11 on 2026-02-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payouts", "0003_payout_audit_log"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payoutrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED"])
                ),
                name="payout_request_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__in", ("RUB", "USD", "EUR", "GBP", "KZT"))),
                name="payout_request_allowed_currency",
            ),
        ),
    ]
